### ISSUE TITLE
How to train the model on my own dataset?

### ISSUE THREAD

**Issue by BiQiWHU** [chou141253/FGVC-PIM#14]
Thanks for your code, it is really a nice work!
However, I found multiple troubles when adapting the code to my own data.
I have already: 1) changed the class number in the config.py and set the args in CMD; 2) the inputted image size has been changed following former issues in this Github page.
![QQ图片20220416123249](https://user-images.githubusercontent.com/23723230/163671721-3c14e2f8-2630-4359-9573-7ebb77d8d58d.png)
![QQ图片20220416123320](https://user-images.githubusercontent.com/23723230/163671722-1326640a-86bd-4684-90ee-2f37612c6bac.png)

However, after changing these two aspects, the results are still misleading and confusing. 
So, may I ask, if using the model on one's own dataset, how many issues do I need to change?

**Comment by chou141253** [comment]
We release new scripts and successfully implement them on other fine-grained visual recognition tasks (some medical tasks). Please check the new code and if you have any questions, please let us know, thanks.
