### ISSUE TITLE
Som questions about the paper.

### ISSUE THREAD

**Issue by KKIverson** [chou141253/FGVC-PIM#23]
![image](https://user-images.githubusercontent.com/49222488/176608456-7e439ac7-4af7-4326-a2aa-0a962f37bf97.png)
2 of Ls in these equations?

![image](https://user-images.githubusercontent.com/49222488/176608573-1b1de387-d97f-485c-b190-ad060e118819.png)
L or lambda?

![image](https://user-images.githubusercontent.com/49222488/176608738-457a0605-63c1-49a2-a867-14afce442066.png)
C or C'? Before or after the fc layer?

**Comment by KKIverson** [comment]
https://arxiv.org/pdf/2202.03822.pdf

**Comment by KKIverson** [comment]
I think those mistakes mentioned above are huge ones, or maybe I misunderstand the architecture design in this paper? 
Can you explain this to me ? Thanks.

**Comment by chou141253** [comment]
L or lambda? --> lambda
C or C'? --> C
My bad!! We will modify it.
Thanks a lot

**Comment by chou141253** [comment]
And the old version (--> /v0/) seems more stable.

**Comment by KKIverson** [comment]
> And the old version (--> /v0/) seems more stable.

This one ?
![image](https://user-images.githubusercontent.com/49222488/176612182-8a917431-1edc-45b2-8083-73d1216febce.png)
Why don't you make a branch called v0 in this repo? ^_^

**Comment by chou141253** [comment]
Yes
