### ISSUE TITLE
Very good work. Can I extract this PIM module separately and add it to my own model?

### ISSUE THREAD

**Issue by scar-on** [chou141253/FGVC-PIM#4]

**Comment by chou141253** [comment]
Sure! And if you have any questions, please let me know. You can also send an email to [ball60304@gmail.com](ball60304@gmail.com).

**Comment by kwangabc** [comment]
Have you successfully integrated into a module? If so, can I use it in my code？

**Comment by chou141253** [comment]
We update our code, thanks! [--> how to build model](https://github.com/chou141253/FGVC-PIM/blob/master/how_to_build_pim_model.ipynb)
