### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by wangyifan97** [chou141253/FGVC-PIM#5]
I want to run the train.py to my datasets , but it is error
`RuntimeError: "max_cpu" not implemented for 'Half'`

**Comment by chou141253** [comment]
please comment out https://github.com/chou141253/FGVC-PIM/blob/3ecf29c496c85b92150c73de65c148322d52ed19/train.py#L147 and https://github.com/chou141253/FGVC-PIM/blob/3ecf29c496c85b92150c73de65c148322d52ed19/train.py#L161 and https://github.com/chou141253/FGVC-PIM/blob/3ecf29c496c85b92150c73de65c148322d52ed19/train.py#L165 and https://github.com/chou141253/FGVC-PIM/blob/3ecf29c496c85b92150c73de65c148322d52ed19/train.py#L395

than change https://github.com/chou141253/FGVC-PIM/blob/3ecf29c496c85b92150c73de65c148322d52ed19/train.py#L165 to 

> optimizer.step()
