### ISSUE TITLE
Swin-T and Resolution

### ISSUE THREAD

**Issue by xiang-jian-wen** [chou141253/FGVC-PIM#7]
Hi, Thanks for your excellent work,  i have a question, i just find the pre-training model Swin_t with pre-training on i1k and resolution 224, can you provide the link to download the pre-training model of swin_t in the paper?

**Comment by chou141253** [comment]
We use the imagenet22k pre-trained model provided by [timm](https://github.com/rwightman/pytorch-image-models).

**Comment by xiang-jian-wen** [comment]
> We use the imagenet22k pre-trained model provided by [timm](https://github.com/rwightman/pytorch-image-models).

Thank you for your reply！ I still have a question.  Dose the Swin-T you marked in your paper refers to the officially published tiny size model (Swin-T)？ But the Swin-L model is used in your published code.  Thank you！

**Comment by chou141253** [comment]
Swin-T means Swin Transformer. We would change the abbreviation of swin-transformer, thanks for your reply.
