### ISSUE TITLE
NAbirds dataset

### ISSUE THREAD

**Issue by 20713** [chou141253/FGVC-PIM#8]
Hello, can you provide the data set of NAbirds? The official website can't download it. Thank you very much

**Comment by chou141253** [comment]
Sure, [https://drive.google.com/file/d/1pf7OX9F-oiePrnZgl40vK7T0Ljo4vYyU/view?usp=sharing](https://drive.google.com/file/d/1pf7OX9F-oiePrnZgl40vK7T0Ljo4vYyU/view?usp=sharing)

**Comment by xiang-jian-wen** [comment]
Hello sir，I cannot download NAbird data set from the official website. The download link above is invalid. Could you please provide a new download link? Thank you very much!

**Comment by 20713** [comment]
> Hello sir，I cannot download NAbird data set from the official website. The download link above is invalid. Could you please provide a new download link? Thank you very much!

you can download from my baidunetdisk in the csdn blog https://blog.csdn.net/hb_learing/article/details/124013803. No thanks.
